---
# Handlers for common role

- name: restart sshd
  systemd:
    name: ssh
    state: restarted
    daemon_reload: yes

- name: restart sshd alternative
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
  ignore_errors: yes

- name: reload locale
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8