---
# Handlers for common role

- name: restart sshd
  systemd:
    name: ssh
    state: restarted
    daemon_reload: yes

- name: restart sshd alternative
  service:
    name: ssh
    state: restarted

- name: update resolvconf
  command: resolvconf -u
  become: true

- name: reload locale
  command: locale-gen
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
  ignore_errors: yes

- name: reload locale
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8