- name: Create and configure Proxmox VMs
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_config:
      - id: 101
        name: k8s-master
        ip: 192.168.10.101
      - id: 102
        name: k8s-node1
        ip: 192.168.10.102
      - id: 103
        name: k8s-node2
        ip: 192.168.10.103

  tasks:
    - name: Stop existing VMs if running
      command: qm stop {{ item.id }}
      loop: "{{ vm_config }}"
      ignore_errors: yes

    - name: Wait for VMs to stop
      pause:
        seconds: 5

    - name: Destroy existing VMs
      command: qm destroy {{ item.id }}
      loop: "{{ vm_config }}"
      ignore_errors: yes

    - name: Wait to ensure cleanup is complete
      pause:
        seconds: 5

    - name: Create VMs
      include_tasks: create_vm.yml
      loop: "{{ vm_config }}"
      loop_control:
        loop_var: vm
