apiVersion: v1
kind: Service
metadata:
  name: dev-guide
  namespace: dev-guide
  labels:
    app: dev-guide
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: dev-guide

