apiVersion: v1
kind: Service
metadata:
  name: dev-guide
  namespace: dev-guide
  labels:
    app: dev-guide
spec:
  type: ClusterIP  # Ingress経由でアクセスするためClusterIPに変更
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dev-guide

